# Dockerfile — ${TOOL_NAME} v${VERSION}
# Tool type: cuda / python-ml (GPU-enabled)
# Maintainer: ${MAINTAINER}
# Generated by docker-hpc skill

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="${TOOL_NAME}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.maintainer="${MAINTAINER}" \
      org.opencontainers.image.description="${TOOL_NAME} ${VERSION} — GPU-enabled, HPC scientific computing"

# Install mamba into CUDA base (CUDA images don't ship conda)
RUN apt-get update && apt-get install -y --no-install-recommends wget bzip2 ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && wget -qO /tmp/miniforge.sh \
       https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh \
    && bash /tmp/miniforge.sh -b -p /opt/conda \
    && rm /tmp/miniforge.sh \
    && /opt/conda/bin/mamba clean --all -y

ENV PATH=/opt/conda/bin:$$PATH

# Layer 2: conda packages
${CONDA_INSTALL}

# Layer 3: pip packages
${PIP_INSTALL}

# Non-root user for HPC compatibility
RUN useradd -m -s /bin/bash biouser
USER biouser

# Library resolution for GPU tools
ENV LD_LIBRARY_PATH=/opt/conda/lib:$$LD_LIBRARY_PATH

# Validation
RUN ${VALIDATION_CMD}

ENTRYPOINT ["${TOOL_NAME}"]
CMD ["--help"]
