# Dockerfile — ${TOOL_NAME} v${VERSION}
# Tool type: ont (Oxford Nanopore tools — dorado, modkit, pod5)
# Maintainer: ${MAINTAINER}
# Generated by docker-hpc skill

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="${TOOL_NAME}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.maintainer="${MAINTAINER}" \
      org.opencontainers.image.source="https://github.com/nanoporetech/${TOOL_NAME}" \
      org.opencontainers.image.licenses="Oxford Nanopore Technologies PLC. Public License Version 1.0" \
      org.opencontainers.image.description="${TOOL_NAME} ${VERSION} — ONT long-read analysis for HPC"

# Add any supplementary tools on top of the ONT base image
# (samtools, bedtools, etc. — only if the base doesn't already include them)
${CONDA_INSTALL}

# pip packages (e.g. pod5, pycoQC)
${PIP_INSTALL}

# Validation — confirm the primary ONT tool is reachable
RUN ${VALIDATION_CMD}

# ONT base images run as root by default; add non-root user for HPC bind-mount safety
RUN useradd -m -s /bin/bash biouser 2>/dev/null || true
USER biouser

ENV PATH=/opt/conda/bin:/usr/local/bin:$$PATH

ENTRYPOINT ["${TOOL_NAME}"]
CMD ["--help"]
