# Dockerfile — ${TOOL_NAME} v${VERSION}
# Tool type: r (R / Bioconductor analysis environment)
# Maintainer: ${MAINTAINER}
# Generated by docker-hpc skill

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="${TOOL_NAME}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.maintainer="${MAINTAINER}" \
      org.opencontainers.image.description="${TOOL_NAME} ${VERSION} — R/Bioconductor HPC environment"

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install mamba for any non-R conda packages
RUN wget -qO /tmp/miniforge.sh \
    https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh \
    && bash /tmp/miniforge.sh -b -p /opt/conda \
    && rm /tmp/miniforge.sh \
    && /opt/conda/bin/mamba clean --all -y

ENV PATH=/opt/conda/bin:$$PATH

# Conda packages (non-R tools)
${CONDA_INSTALL}

# Bioconductor packages via BiocManager
${BIOC_INSTALL}

# CRAN packages
${CRAN_INSTALL}

# pip packages (if any)
${PIP_INSTALL}

# Non-root user
RUN useradd -m -s /bin/bash biouser
USER biouser

# Validation
RUN ${VALIDATION_CMD}

ENTRYPOINT ["Rscript"]
CMD ["--help"]
