#!/bin/bash
# Log every SLURM job submitted via MCP tools to a human-readable markdown file.
# PostToolUse hook — fires after slurm_submit_job or slurm_submit_batch.
# Exit 0 always (logging should never block).
# Author: Samuel Ahuno
# Date: 2026-02-21

# $SLURM_JOB_LOG, else the site profile, else a project-local log. The previous
# absolute fallback existed on one machine; elsewhere the append silently failed.
LOG_FILE="${SLURM_JOB_LOG:-}"
if [ -z "$LOG_FILE" ] && [ -n "${SITE_CONFIG:-}" ]; then
  LOG_FILE=$(grep -A2 '^logs:' "$SITE_CONFIG/paths.yaml" 2>/dev/null | awk '/slurm_submissions:/{print $2}')
fi
LOG_FILE="${LOG_FILE:-./slurm_logs/claude_submissions.md}"
# Portable JSON parsing (prefers jq, falls back to python3, warns loudly
# if neither exists rather than silently passing everything through).
. "${BASH_SOURCE[0]%/*}/lib/json.sh"
json_backend_check || exit 0

TOOL_INPUT=$(cat)

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

# Initialize log file with header if new
if [ ! -f "$LOG_FILE" ]; then
    cat > "$LOG_FILE" << 'HEADER'
# Claude Code SLURM Job Submissions Log

Auto-generated by PostToolUse hook. Every job submitted through the SLURM MCP
server is logged here for tracking and reproducibility.

---

HEADER
fi

# PostToolUse JSON structure:
#   .tool_response = JSON string containing {"result": "<JSON string of actual data>"}
# So we need: .tool_response | fromjson | .result | fromjson -> actual fields

# The payload is double-encoded: .tool_response is a JSON string whose .result
# is another JSON string. Flattened by a helper so this hook needs no jq — the
# safety hooks dropped that dependency and a logger that silently stops logging
# has the same problem for the audit trail.
FIELDS=$(printf '%s' "$TOOL_INPUT" | python3 "${BASH_SOURCE[0]%/*}/lib/parse_slurm_response.py" 2>/dev/null)
[ -z "$FIELDS" ] && exit 0

JOB_ID=$(sed -n '1p'  <<< "$FIELDS")
JOB_NAME=$(sed -n '2p' <<< "$FIELDS")
COMMAND=$(sed -n '3p'  <<< "$FIELDS")
DRY_RUN=$(sed -n '4p'  <<< "$FIELDS")
ERROR=$(sed -n '5p'    <<< "$FIELDS")
SUBMITTED=$(sed -n '6p' <<< "$FIELDS")

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
SESSION_DIR=$(json_get "$TOOL_INPUT" cwd)

# Log dry-run
if [ "$DRY_RUN" = "true" ]; then
    cat >> "$LOG_FILE" << EOF
### [DRY RUN] — ${JOB_NAME:-unnamed}
- **Time:** ${TIMESTAMP}
- **Name:** ${JOB_NAME}
- **Command:** \`${COMMAND}\`

EOF
    exit 0
fi

# Log single job submission
if [ -n "$JOB_ID" ] && [ "$JOB_ID" != "null" ]; then
    cat >> "$LOG_FILE" << EOF
### Job ${JOB_ID} — ${JOB_NAME}
- **Submitted:** ${TIMESTAMP}
- **Job ID:** ${JOB_ID}
- **Name:** ${JOB_NAME}
- **Working dir:** ${SESSION_DIR}
- **Command:** \`${COMMAND}\`
- **Status:** Submitted

EOF
    exit 0
fi

# Log batch submissions
if [ -n "$SUBMITTED" ] && [ "$SUBMITTED" != "null" ]; then
    TOTAL=$(sed -n '7p' <<< "$FIELDS")
    JOBS=$(sed -n '8,$p' <<< "$FIELDS")
    cat >> "$LOG_FILE" << EOF
### Batch Submission — ${SUBMITTED}/${TOTAL} jobs
- **Submitted:** ${TIMESTAMP}
- **Working dir:** ${SESSION_DIR}
${JOBS}

EOF
    exit 0
fi

# Log errors
if [ -n "$ERROR" ] && [ "$ERROR" != "null" ]; then
    cat >> "$LOG_FILE" << EOF
### [ERROR] Submission Failed
- **Time:** ${TIMESTAMP}
- **Error:** ${ERROR}

EOF
fi

exit 0
