LOCAL_SOFTWARE_PATH_PERSONAL: "/data1/greenbab/users/ahunos/apps/containers/"
LOCAL_SOFTWARE_PATH_GROUP: "/data1/greenbab/software/images"
DOCKERHUB_USERNAME: "sahuno"
DOCKERHUB_personal_repo: https://hub.docker.com/repositories/sahuno
GITHUB_USERNAME: "sahuno"
ONT_software_container_container_name: "sahuno/onttools"
DOCKER_HUB_CONTAINERS: {
  {
    "name": "Onttools v3.0; samtools, dorado, bedtools",
    "value": "sahuno/onttools:v3.0"
  },
  {
    "name": "Onttools Latest; samtools, dorado, bedtools",
    "value": "sahuno/onttools:latest"
  },
  {
    "name": "Modkit Latest",
    "value": "sahuno/modkit:latest"
  },
  {
    "name": "Bedtools Latest",
    "value": "sahuno/bedtools:latest"
  },
  {
    "name": "Bedtools Suite v2.31.1",
    "value": "sahuno/bedtools_suite:v2.31.1"
  },
  {
    "name": "UCSC Utils Latest",
    "value": "sahuno/ucsc_utils:latest"
  },
  {
    "name": "Mosdepth Multiarch and multiqc",
    "value": "sahuno/mosdepth:multiarch"
  },
  {
    "name": "Sniffles 2.6.2",
    "value": "sahuno/sniffles:2.6.2"
  },
  {
    "name": "Numpyroml Latest",
    "value": "sahuno/numpyroml:latest"
  }
}
