# Dockerfile — ${TOOL_NAME} v${VERSION}
# Tool type: biocli / generic (conda-installable)
# Maintainer: ${MAINTAINER}
# Generated by docker-hpc skill

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="${TOOL_NAME}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.maintainer="${MAINTAINER}" \
      org.opencontainers.image.description="${TOOL_NAME} ${VERSION} for HPC scientific computing"

# Layer 1: system deps (rarely change — cache-friendly)
RUN apt-get update && apt-get install -y --no-install-recommends \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Layer 2: conda packages (changes on version bumps)
${CONDA_INSTALL}

# Layer 3: pip packages (if any)
${PIP_INSTALL}

# Layer 4: non-root user for HPC compatibility
RUN useradd -m -s /bin/bash biouser
USER biouser

# Explicit PATH — don't rely on shell profiles in non-interactive exec
ENV PATH=/opt/conda/bin:$$PATH

# Layer 5: validation — fails the build if the tool didn't install correctly
RUN ${VALIDATION_CMD}

ENTRYPOINT ["${TOOL_NAME}"]
CMD ["--help"]
