#!/bin/bash
# Log every SLURM job submitted via MCP tools to a human-readable markdown file.
# PostToolUse hook — fires after slurm_submit_job or slurm_submit_batch.
# Exit 0 always (logging should never block).
# Author: Samuel Ahuno
# Date: 2026-02-21

LOG_FILE="${SLURM_JOB_LOG:-/data1/greenbab/users/ahunos/slurm_logs/claude_submissions.md}"
TOOL_INPUT=$(cat)

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

# Initialize log file with header if new
if [ ! -f "$LOG_FILE" ]; then
    cat > "$LOG_FILE" << 'HEADER'
# Claude Code SLURM Job Submissions Log

Auto-generated by PostToolUse hook. Every job submitted through the SLURM MCP
server is logged here for tracking and reproducibility.

---

HEADER
fi

# PostToolUse JSON structure:
#   .tool_response = JSON string containing {"result": "<JSON string of actual data>"}
# So we need: .tool_response | fromjson | .result | fromjson -> actual fields

PARSED=$(echo "$TOOL_INPUT" | jq -r '.tool_response' | jq -r '.result' | jq '.' 2>/dev/null)

if [ -z "$PARSED" ] || [ "$PARSED" = "null" ]; then
    exit 0
fi

# Extract fields
JOB_ID=$(echo "$PARSED" | jq -r '.job_id // empty')
JOB_NAME=$(echo "$PARSED" | jq -r '.job_name // empty')
COMMAND=$(echo "$PARSED" | jq -r '.command // empty')
DRY_RUN=$(echo "$PARSED" | jq -r '.dry_run // false')
ERROR=$(echo "$PARSED" | jq -r '.error // empty')
SUBMITTED=$(echo "$PARSED" | jq -r '.submitted // empty')

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
SESSION_DIR=$(echo "$TOOL_INPUT" | jq -r '.cwd // empty')

# Log dry-run
if [ "$DRY_RUN" = "true" ]; then
    cat >> "$LOG_FILE" << EOF
### [DRY RUN] — ${JOB_NAME:-unnamed}
- **Time:** ${TIMESTAMP}
- **Name:** ${JOB_NAME}
- **Command:** \`${COMMAND}\`

EOF
    exit 0
fi

# Log single job submission
if [ -n "$JOB_ID" ] && [ "$JOB_ID" != "null" ]; then
    cat >> "$LOG_FILE" << EOF
### Job ${JOB_ID} — ${JOB_NAME}
- **Submitted:** ${TIMESTAMP}
- **Job ID:** ${JOB_ID}
- **Name:** ${JOB_NAME}
- **Working dir:** ${SESSION_DIR}
- **Command:** \`${COMMAND}\`
- **Status:** Submitted

EOF
    exit 0
fi

# Log batch submissions
if [ -n "$SUBMITTED" ] && [ "$SUBMITTED" != "null" ]; then
    TOTAL=$(echo "$PARSED" | jq -r '.total // 0')
    JOBS=$(echo "$PARSED" | jq -r '.jobs[]? | "  - Job \(.job_id // "?") — \(.script // "unknown") (step \(.step // "?"))"' 2>/dev/null)
    cat >> "$LOG_FILE" << EOF
### Batch Submission — ${SUBMITTED}/${TOTAL} jobs
- **Submitted:** ${TIMESTAMP}
- **Working dir:** ${SESSION_DIR}
${JOBS}

EOF
    exit 0
fi

# Log errors
if [ -n "$ERROR" ] && [ "$ERROR" != "null" ]; then
    cat >> "$LOG_FILE" << EOF
### [ERROR] Submission Failed
- **Time:** ${TIMESTAMP}
- **Error:** ${ERROR}

EOF
fi

exit 0
